version: "2"

services:
  zookeeper-master:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1-master:
    image: "bitnami/kafka:2.6.0"
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-master:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka2-master:
    image: "bitnami/kafka:2.6.0"
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-master:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka3-master:
    image: "bitnami/kafka:2.6.0"
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-master:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      
  zookeeper-slave:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2182:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1-slave:
    image: "bitnami/kafka:2.6.0"
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-slave:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka2-slave:
    image: "bitnami/kafka:2.6.0"
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-slave:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka3-slave:
    image: "bitnami/kafka:2.6.0"
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-slave:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka-mm2:
    image: "bitnami/kafka-mm2-jar:2.6.0"
    entrypoint: [ "/opt/bitnami/kafka/bin/connect-mirror-maker.sh","/tmp/connect-mirror-maker.properties"]
    volumes:
      - '/Users/qichen/workspace/data/kafka:/tmp'
